name: autofix.ci # Required (https://autofix.ci/setup)

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'

  pull_request:
    branches:
      - main
    paths-ignore:
      - '**.md'

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

env:
  NUXT_PUBLIC_API_URL: 'http://localhost:8000'

jobs:
  lint-and-format:
    name: Lint & Format
    runs-on: ubuntu-latest

    steps:
      - name: Checkout current branch
        uses: actions/checkout@v4

      - name: Setup bun
        uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun install

      - name: Lint
        run: |
          if [ "${{ github.event_name }}" = "pull_request" ]; then
            bun run lint:fix
          else
            bun run lint
          fi

      - name: Format
        run: |
          if [ "${{ github.event_name }}" = "pull_request" ]; then
            bun run format:fix
          else
            bun run format
          fi

      - name: Autofix
        if: github.event_name == 'pull_request'
        uses: autofix-ci/action@v1.3

  # Some errors only happens at build-time so we build to catch them early.
  build:
    name: Build
    runs-on: ubuntu-latest
    needs: [lint-and-format]

    steps:
      - name: Checkout current branch
        uses: actions/checkout@v4

      - name: Setup bun
        uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun install

      - name: build
        run: bun run build
